### ISSUE TITLE
Training code of model

### ISSUE THREAD

**Issue by H-HChen** [yzqin/s4g-release#1]
I haven't seen the training code of this model from current release. 
Will there be an example code for future release?

**Comment by yzqin** [comment]
The network work files are included in the repo. The entry code for training will be public soon.

**Comment by maximiliangilles** [comment]
Hi @yzqin,

I wanted to get back to you regarding the custom training. Is there an update here if you will are willing to share the code?

Thanks a lot!

Best,

Maximilian

**Comment by yzqin** [comment]
Hi @maximiliangilles and @H-HChen,

Thanks for your question and interest. I am sorry that the project and code is developed in 2019 and it has been a long time since I wrote this code. It is little bit tricky to make sure everything runs smoothly in the right environment. I can send you the original training code used during paper submission by email if you want but it is very hard to incoprate the cleaned training code inside this repo. Sorry for the inconvenience.

**Comment by yzqin** [comment]
https://drive.google.com/file/d/184tnRAHz9dnzhz86Jfcs35t7mCr8BlE5/view?usp=sharing
