### ISSUE TITLE
how datasets generate

### ISSUE THREAD

**Issue by Twilight89** [yzqin/s4g-release#2]
Hi~
Could you give a brief introduction about how to generate the training data by using your data_gen code?

Hope for reply,
Thanks

**Comment by yzqin** [comment]
Sorry for the late reply. You can refer to the updated README instruction here for data generation `https://github.com/yzqin/s4g-release#data-generation`.

Thanks!

**Comment by xins981** [comment]
@yzqin Hi, yuzhe. through look at code, the trainning scene data gen seem follow this:
1 scale_objects.py scale 3D model
2 plain_vhacd.py convex decomposition
3 wrl_to_stl.py to stl file
4 table_env.py simulate scene and save obj pose in scene
5 data_object_contact_point_generator.py gen grasp configure based 3d model
6 data_generator.py final traing scene and label
this understand is right?

besides, the step 1, 3 need blender to process model. but the blender is not easy work for me  in ubuntu 18.04, python 3.8 also try py3.7.  the error is
/snap/blender/3915/blender: symbol lookup error: /snap/blender/3915/lib/libembree4.so.4: undefined symbol: _ZN3tbb10interface78internal20isolate_within_arenaERNS1_13delegate_baseEl

can you provide your environment info or the processed files? any advice is welcome, thanks a lot advance!

**Comment by yzqin** [comment]
Hi @xins981, your comprehension seems to be on point. The complications you're encountering appear to be linked with your Blender setup, not this repository. Rather than using `snap` for your Blender installation, I recommend exploring other methods. Additionally, you might want to consider installing the Blender Python package directly from this [link ↗](https://pypi.org/project/bpy/).

Also blender uses an embeded python rather than you system python, so maybe it is the cause for your issue.

**Comment by xins981** [comment]
@yzqin, thanks! as you say, in blender desktop terminal, the code is ok, but this run only line by line rather a py file.

it is strange that I following [link](https://pypi.org/project/bpy/) install bpy in blender built-in python. and run like your recommend "# example: blender --python wrl_to_stl.py -- /wrl /convex_stl", then throw error "libembree4.so.4: undefined symbol...". 
have any difference betweent two run manners?

**Comment by xins981** [comment]
run script wrl_to_stl.py in blender desktop Text_Editor done.
