### ISSUE TITLE
Importance sampling vs Non-maximum Suppression

### ISSUE THREAD

**Issue by kimanton** [yzqin/s4g-release#8]
Hi @yzqin again
Sorry to constantly bothering you, but I have another question
In your paper you mention Non-maximum Suppression and Grasp Sampling algorithm. I am wondering if [this](https://github.com/yzqin/s4g-release/blob/b684ade8fa32ddb55d03a6a36fcfe7f1dc81ca1c/inference/grasp_proposal/grasp_detector.py#L236) part of your code is an equivalent implementation?

Also, would you be able to explain what function $g(s_h)$ does in Algorithm 1 of your paper? And what is the meaning of variable $p_k$, is it a score for a grasp?

Also I assume that in this line there is a typo and there should be another "and" between H and dist, is it? ![image](https://user-images.githubusercontent.com/47267737/211319520-ebbb7194-2721-49ab-9640-84ef56424a78.png)

I added picture of the entire algorithm for convenience
![image](https://user-images.githubusercontent.com/47267737/211317982-5e50017d-f742-4941-a902-e72f07e51c88.png)

Btw, I did transform point cloud as you suggested and it worked like a charm, thank you again

**Comment by kimanton** [comment]
I also can't get good results when using [GraspDetector](https://github.com/yzqin/s4g-release/blob/b684ade8fa32ddb55d03a6a36fcfe7f1dc81ca1c/inference/grasp_proposal/grasp_detector.py#L22) class, actually no results most of the time.
I get much better results with [grasp_proposal_test.py](https://github.com/yzqin/s4g-release/blob/master/inference/grasp_proposal/grasp_proposal_test.py), although they are loading the same model and I feed both with [2638_view_0.p](https://github.com/yzqin/s4g-release/blob/master/inference/2638_view_0.p) that you provided

Is there something specific I should do to use [GraspDetector](https://github.com/yzqin/s4g-release/blob/b684ade8fa32ddb55d03a6a36fcfe7f1dc81ca1c/inference/grasp_proposal/grasp_detector.py#L22)? Like some tweaking before using?


Some additional info if it helps in any way
Here is sample code I use to test [GraspDetector](https://github.com/yzqin/s4g-release/blob/b684ade8fa32ddb55d03a6a36fcfe7f1dc81ca1c/inference/grasp_proposal/grasp_detector.py#L22)
```
import os
import torch

import numpy as np
import open3d

from grasp_proposal.grasp_detector import GraspDetector
from grasp_proposal.cloud_processor.cloud_processor import CloudPreProcessor
from grasp_proposal.utils.grasp_visualizer import GraspVisualizer

single_training_data = np.load("../2638_view_0.p", allow_pickle=True)
data = single_training_data["point_cloud"]
pcd_m = open3d.geometry.PointCloud(open3d.utility.Vector3dVector(data.T))

detector = GraspDetector()
poses, scores = detector.detect(data, num_selected=5, collision_check=True, score_threshold=0.7, verticalness_threshold=0.2)

print("Scores: \n", scores,)
print("Pose 0: \n", poses[0])

visualizer = GraspVisualizer(pcd_m)
visualizer.add_multiple_poses(poses)
visualizer.visualize()
```
I am able to get results like this
![image](https://user-images.githubusercontent.com/47267737/211329763-da2386eb-0b08-4356-952b-cd3408686357.png)

And this is a result from  [grasp_proposal_test.py](https://github.com/yzqin/s4g-release/blob/master/inference/grasp_proposal/grasp_proposal_test.py)
![image](https://user-images.githubusercontent.com/47267737/211329575-83be1c28-4bff-4aff-a4e8-dffc36b3a2ff.png)

**Comment by yzqin** [comment]
@kimanton 

This is the reply to your first question (Non-maximum Suppression). The code you linked [here[(https://github.com/yzqin/s4g-release/blob/b684ade8fa32ddb55d03a6a36fcfe7f1dc81ca1c/inference/grasp_proposal/grasp_detector.py#L236) is not related to NMS. It is simply sort and sample the initial set of grasp poses based on predicted scores. The NMS step is performed after the output of the whole function.

The NMS part is heavily coupled with real-robot execution part (since we will only sample a new pose when the motion planning or controller execution fails) and is not included in this github repo. The NMS part is very straight forward and standard in detection to implement and you can find many existing NMS implementation from detection code on Github, e.g. [this one](https://github.com/amusi/Non-Maximum-Suppression/blob/e054bba6973112d784394470bf2e552d929843be/nms.py#L18). You can simply replace the 2D distance function using the 3D distance function.

**Comment by kimanton** [comment]
Thank you for explanation, I understand now
