### ISSUE TITLE
The transform about the rotation matrices 

### ISSUE THREAD

**Issue by candace3698** [yzqin/s4g-release#9]
Hi, @yzqin 
I am interested in your project. However, I met several questions studying the paper and implementing the code.

How should I understand the rotation matrices I get from the output of the algorithm? I know that they are the poses predicted by the network, but it is the transform from what to the grasping pose?

According to the question above, I am wondering that if I want to implement the grasp how many transform I need to do? base to ee, ee to gripper, camera to base? Does it means that I should transform the grasping pose(camera coordinate?) I get from the network to robot coordinate?

Thank you

**Comment by yzqin** [comment]
hi @candace3698 

It is the transform from world coordinate to the grasp coordinate. The xyz axis definition follow the same convention as previous work like [GPD](https://arxiv.org/abs/1706.09911) and [PointNetGPD](https://arxiv.org/abs/1809.06267)

ee, ee to gripper, camera to base. The world frame is only used to per-process the data, i.e. remove point outside of the table space so that it will not generate a grasp pose far away.
